################################################################################
# Author: Peyton Chandarana
# Date:   
# Use:    For use in CSCE 513
################################################################################
CC=gcc

all: heapsort quicksort

quicksort:
	$(CC) quicksort.c -o quicksort -lm

heapsort:
	$(CC) heapsort.c -o heapsort -lm

clean:
	rm -r heapsort quicksort m5out* 
